# Generated by Django 6.1.1 on 2026-09-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_portal', '0002_alter_agentprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='aadhaar_number',
            field=models.CharField(blank=True, default='', help_text='12-digit Aadhaar number', max_length=12),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='address_line1',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='address_line2',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='insurance_company',
            field=models.CharField(blank=True, choices=[('ICICI', 'ICICI Lombard'), ('STAR', 'Star Health'), ('NIVA_BUPA', 'Niva Bupa')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='pan_number',
            field=models.CharField(blank=True, default='', help_text='10-character PAN (e.g. ABCDE1234F)', max_length=10),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='pincode',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='state',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
